# Generated by Django 5.0.6 on 2024-06-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
